visgl/deck.gl-community

.github/workflows/test.yaml
Copied from deck.gl's `test.yaml`, with modifications. Currently `yarn test` just runs a linter, but this will run unit tests as well after #31.
=> chore(ci): Add CI

.eslintrc.cjs, yarn.lock
Loosens the linter settings a bit to bring this down to a more manageable 300 errors and warnings. These can be tightened up after current errors are addressed, perhaps more strictly for production code than for test code.
=> chore(lint): Loosen stricter eslint warnings

modules/editable-layers/src/index.ts
This little PR exports the util functions that were previously available under `@nebula.gl/edit-modes`. 
These are useful for implementing custom edit modes or extending upon existing ones. 
Please let me know if there is a different naming convention that would be preferred.
=> Exported edit-mode utils

examples/arrow-layers/linestring/package.json, examples/arrow-layers/multilinestring/package.json, examples/arrow-layers/multipoint/package.json, examples/arrow-layers/multipolygon/package.json, examples/arrow-layers/point/package.json, examples/arrow-layers/polygon/package.json, examples/arrow-layers/text/package.json, examples/arrow-layers/trips/package.json
The examples in the examples/arrow-layers need an extra `../` in the volta path to reach the root
=> Fix examples/arrow-layers volta path

dev-docs/RFCs/editable-layers/react-map-gl-draw.md, examples/editable-layers/advanced/src/example.tsx, examples/editable-layers/editable-h3-cluster-layer/index.tsx, examples/editable-layers/editor/example.tsx, examples/editable-layers/sf/example.tsx
This light basemap does the job of showcasing the examples perfectly fine.
=> Use Carto positron style

examples/editable-layers/advanced/index.html, examples/editable-layers/advanced/package.json, examples/editable-layers/advanced/src/app.tsx, examples/editable-layers/advanced/src/example.tsx, examples/editable-layers/codesandbox/getting-started/index.js, examples/editable-layers/codesandbox/getting-started/package.json, examples/editable-layers/codesandbox/world-heritage/index.js, examples/editable-layers/editable-h3-cluster-layer/index.html, examples/editable-layers/editable-h3-cluster-layer/index.tsx, examples/editable-layers/editable-h3-cluster-layer/package.json, examples/editable-layers/editor/example.tsx, examples/editable-layers/editor/index.html, examples/editable-layers/editor/package.json, examples/editable-layers/overlays/example.tsx, examples/editable-layers/overlays/index.html, examples/editable-layers/overlays/package.json, examples/editable-layers/sf/example.tsx, examples/editable-layers/sf/index.html, examples/editable-layers/sf/package.json
This allow running all the /examples/editable-layers/ without api keys.
=> Use maplibre in examples/editable-layers

examples/editable-layers/advanced/src/example.tsx, examples/editable-layers/codesandbox/getting-started/index.js, examples/editable-layers/codesandbox/world-heritage/index.js, examples/editable-layers/editable-h3-cluster-layer/index.tsx, examples/editable-layers/editor/example.tsx, examples/editable-layers/overlays/example.tsx, examples/editable-layers/sf/example.tsx, website/src/doc-demos/demo-base.js
instead of mapLib={MapLibre}, just use the `import StaticMap from "react-map-gl/maplibre"`
=> Use maplibre export from react-map-gl

website/src/components/home/index.jsx
the "get started" on the landing page leads to a 404
=> Fix landing page link

website/package.json, website/tsconfig.json, website/yarn.lock
This will add [typescript support](https://docusaurus.io/docs/typescript-support) for the BrowserOnly which is used here:
- https://github.com/visgl/deck.gl-community/pull/90
=> Add docusaurus types

examples/editable-layers/advanced/src/example.tsx, modules/editable-layers/src/edit-modes/draw-90degree-polygon-mode.ts
This example doesn't crash anymore, but it still doesn't add the polygon on completion.
=> Fix crash in 90 degree editable-layers example

modules/editable-layers/src/edit-modes/draw-90degree-polygon-mode.ts
This pull request fixes drawing polygons with 90 degree angles.
Seems like the issue was running the fake pointer movement even if we were finishing the polygon.
https://github.com/user-attachments/assets/26e888bf-ff6e-4698-84fd-f08d9a4767e5
=> Fix 90 degree polygon drawing

modules/graph-layers/package.json, package.json, yarn.lock
- After upgrading ocular and build settings, Node.js tests failed due to some node import syntax issue.
- Upgrading Node.js
- Also dropping "gl" dependency that slows down installs and causes issues on windows.
=> chore: Upgrade to Node 20, drop "gl" dependency

modules/react/package.json
The URL in npm is pointing to wrong repo. This PR will fix this.
I have attached the screenshot of the current url in the npm.
=> fix: update the url field in @deck.gl-community/react package.json

docs/modules/editable-layers/api-reference/edit-modes/transform-modes.md, modules/editable-layers/src/edit-modes/delete-mode.ts, modules/editable-layers/src/editable-layers/editable-geojson-layer.ts, modules/editable-layers/test/edit-modes/lib/delete-mode.spec.ts
There is currently no way to delete features from a `FeatureCollection` via user interaction.
Introduce a `DeleteMode` class that extends `GeoJsonEditMode`. This mode will:
1. Handle user clicks to identify and remove the selected feature(s) from the `FeatureCollection`.
2. Trigger an `onEdit` callback to update the collection in the application state.
- **delete-mode.ts**: Implement the `DeleteMode` class.
- **delete-mode.test.ts**: Add unit tests to ensure correct functionality.
This will enable users to manage their data more effectively by removing unwanted features.
=> Feat: delete mode for geojson editable layers

docs/modules/editable-layers/api-reference/layers/editable-geojson-layer.md, modules/editable-layers/src/edit-modes/extend-line-string-mode.ts, modules/editable-layers/src/edit-modes/extrude-mode.ts, modules/editable-layers/src/edit-modes/modify-mode.ts, modules/editable-layers/src/edit-modes/resize-circle-mode.ts, modules/editable-layers/src/edit-modes/rotate-mode.ts, modules/editable-layers/src/edit-modes/scale-mode.ts, modules/editable-layers/src/edit-modes/transform-mode.ts, modules/editable-layers/src/edit-modes/translate-mode.ts, modules/editable-layers/src/edit-modes/types.ts, modules/editable-layers/src/edit-modes/utils.ts, modules/editable-layers/src/editable-layers/editable-layer.ts
Hello - thank you for building NebulaGL / `editable-layers`, it is a fantastic library.
This PR contains two small changes:
* Introduces an optional `onCancelPan` prop to `editable-layers`, allowing developers to execute their own logic when NebulaGL determines a map panning operation should be cancelled. This enables the event to propagate to a host mapping framework.
* Adds `event.cancelPan()` invocations for a variety of `EditModes`, ensuring `event.cancelPan` is being called at the appropriate time
=> Adds onCancelPan optional prop and adds more calls to cancelPan

modules/editable-layers/src/editable-layers/editable-geojson-layer.ts, modules/editable-layers/src/index.ts
Exporting EditableGeoJsonLayerProps type and fixing the naming casing between layer and props (fixes #163)
=> Exporting editable geojson layer props and fixing name casing

examples/playground/src/json-configuration.ts
Fix playground example does not crash while typing layers etc.
Applies https://github.com/visgl/deck.gl/pull/9316 to deck.gl-community.
=> fix: Avoid crashing playground example when typing layers, views etc

modules/editable-layers/src/editable-layers/editable-path-layer.ts
Fixes regression introduced by https://github.com/visgl/deck.gl-community/pull/205 (and lack of testing 🙉 ). `pickingUniforms` are already present in deck.gl so we cannot use the same name
=> EditablePathLayer: Rename shader module to avoid clash

modules/experimental/package.json, modules/raster-layers/package.json
I did a pass on all the `package.json` files prior to publishing beta packages and found that raster-layers has never been published. As such I've marked it as private as I assume is not production ready.
FYI the current npm stats for all the modules are:
| Package | Weekly Downloads |
|--------------------------------------|-------------------:|
| @deck.gl-community/arrow-layers | private |
| @deck.gl-community/bing-maps | 1 |
| @deck.gl-community/editable-layers | 12,000 |
| @deck.gl-community/experimental | 50 |
| @deck.gl-community/graph-layers | 3 |
| @deck.gl-community/layers | 10,000 |
| @deck.gl-community/leaflet | private |
| @deck.gl-community/deck.gl-raster | Unpublished |
| @deck.gl-community/react | 100 |
=> Update experimental & raster-layers package.json

lerna.json
To avoid unintended changes when running `yarn publish-beta`
Before:
```
yarn publish-beta
...
npx lerna version prerelease --force-publish --exact --no-commit-hooks
Changes:
- @deck.gl-community/arrow-layers: 9.1.0-beta.0 => 9.1.0-beta.1 (private)
- @deck.gl-community/bing-maps: 9.1.0-beta.0 => 9.1.0-beta.1
- @deck.gl-community/editable-layers: 9.1.0-beta.0 => 9.1.0-beta.1
- @deck.gl-community/experimental: 9.1.0-beta.0 => 9.1.0-beta.1
- @deck.gl-community/graph-layers: 9.1.0-beta.0 => 9.1.0-beta.1
- @deck.gl-community/layers: 9.1.0-beta.0 => 9.1.0-beta.1
- @deck.gl-community/leaflet: 9.1.0-beta.0 => 9.1.0-beta.1 (private)
- @deck.gl-community/deck.gl-raster: 0.3.1 => 0.3.2-alpha.0 (private)
- @deck.gl-community/react: 9.1.0-beta.0 => 9.1.0-beta.1
- @deck.gl-community/template: 0.0.4 => …
```
=> yarn publish: Do not bump in private packages

.ocularrc.js, examples/vite.config.local.mjs
Running `yarn start-local` in examples directories fails with:
```
❯ yarn start-local
failed to load config from /Users/zakjan/code/zakjan/deck.gl-community/examples/vite.config.local.mjs
error when starting dev server:
Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'ocular-dev-tools' imported from /Users/zakjan/code/zakjan/deck.gl-community/examples/vite.config.local.mjs.timestamp-1739689952140-95c3fea2c2856.mjs
at packageResolve (node:internal/modules/esm/resolve:854:9)
at moduleResolve (node:internal/modules/esm/resolve:927:18)
at defaultResolve (node:internal/modules/esm/resolve:1169:11)
at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:542:12)
at ModuleLoader.resolve (node:internal/modules/esm/loader:510:25)
at ModuleLoader.getModuleJob …
```
=> Replace missed occurrences of ocular-dev-tools to @vis.gl/dev-tools

modules/editable-layers/package.json, modules/editable-layers/src/edit-modes/three-click-polygon-mode.ts, modules/editable-layers/src/edit-modes/two-click-polygon-mode.ts, package.json, yarn.lock
For [9.1.0-beta.4](https://www.npmjs.com/package/@deck.gl-community/editable-layers/v/9.1.0-beta.4) version this PR fixes:
```
Failed to load external module @deck.gl-community/editable-layers: SyntaxError: The requested module 'lodash' does not provide an export named 'omit'.
```
I also added `lerna` as devDependency to have the scripts running without installing it globally.
=> Fix lodash import

docs/modules/editable-layers/api-reference/edit-modes/measurement-modes.md
=> docs: fix url to turf distance documentation

modules/editable-layers/src/editable-layers/editable-layer.ts, modules/editable-layers/src/editable-layers/selection-layer.ts, modules/infovis-layers/LICENSE, website/src/docs-sidebar.js
@AnJ-K Thanks for calling this out.
=> fix: Remove stray merge markers

examples/layers/horizon-graph-layer/app.tsx, examples/layers/horizon-graph-layer/index.html, examples/layers/horizon-graph-layer/index.tsx, examples/layers/horizon-graph-layer/package.json, examples/layers/horizon-graph-layer/tsconfig.json, modules/layers/src/horizon-graph-layer/horizon-graph-layer-uniforms.ts, modules/layers/src/horizon-graph-layer/horizon-graph-layer.fs.ts, modules/layers/src/horizon-graph-layer/horizon-graph-layer.ts, modules/layers/src/horizon-graph-layer/horizon-graph-layer.vs.ts, modules/layers/src/horizon-graph-layer/multi-horizon-graph-layer.ts, modules/layers/src/index.ts, yarn.lock
This PR adds support for horizon graph visualizations by introducing `HorizonGraphLayer` and `MultiHorizonGraphLayer`, updates the module exports, and provides an example application to showcase usage.
- Add new horizon graph layer implementations (shaders, uniforms, WebGL resource management).
- Introduce composite `MultiHorizonGraphLayer` for multi-series horizon graphs.
- Update `index.ts` exports and include a fully working example under `examples/layers/horizon-graph-layer`.
=> Horizon Layer

examples/graph-layers/graph-viewer/package.json, website/docusaurus.config.js, website/src/examples-sidebar.js, website/src/examples/infovis-layers/horizon-graph-layer.mdx, website/src/examples/infovis-layers/horizon-graph-layer.tsx
- add Horizon Graph Layer demo for website examples
- register the new demo on the examples sidebar
- load example code lazily on the website
=> Add horizon graph layer website example
